#!/bin/bash
#
#      ▗     ▗     ▗ 
#  ▀▌▌▌▜▘▛▌▛▘▜▘▀▌▛▘▜▘
#  █▌▙▌▐▖▙▌▄▌▐▖█▌▌ ▐▖
#
#

export PRESET="groove"

# load fonts
xset fp+ ~/.fonts
xset fp rehash

# Screen
xrandr --output HDMI1 --auto

# Sources for terminal
xrdb -merge ~/.Xresources

# Wallpaper
nitrogen --restore &

# notification daemon
dunst &

# compositor
compton &

# color temperature
redshift &

# System Tray
cbatticon &
volumeicon &
nm-applet &
clipit &

# Panel
polybar top -c ~/.config/polybar/simplicity
