#!/bin/bash
#
#      ▗     ▗     ▗ 
#  ▀▌▌▌▜▘▛▌▛▘▜▘▀▌▛▘▜▘
#  █▌▙▌▐▖▙▌▄▌▐▖█▌▌ ▐▖
#
#

export PRESET="monokai"

# load fonts
xset fp+ ~/.fonts
xset fp rehash

# Screen
xrandr --output eDP-1 --mode 2560x1440

# Sources for terminal
xrdb -merge ~/.Xresources

# Wallpaper
nitrogen --restore &
#$(wal -i ~/Pictures/15201.jpeg)

# notification daemon
dunst &

# compositor
compton &

# color temperature
redshift &

# System Tray
cbatticon &
volumeicon &
nm-applet &
blueman-applet & 
clipit &

# Panel
tint2 -c ~/.config/tint2/tint2rc
